import { ArrowLeft, BadgeCheck, CalendarCheck, Clock3, Languages, MessageCircle, ShieldCheck, Sparkles, TrendingUp, Users, Zap } from "lucide-react";
import Brand from "@/components/Brand"; import LiveDemo from "@/components/LiveDemo"; import Footer from "@/components/Footer"; import FloatingCTA from "@/components/FloatingCTA"; import { DEMO_URL, WHATSAPP_URL } from "@/config/site";
const outcomes=[[Zap,"الرد الفوري","كل استفسار يحصل على إجابة خلال ثوانٍ."],[TrendingUp,"زيادة الحجوزات","حوّل المحادثات إلى مواعيد مؤكدة بسهولة."],[Users,"ضغط أقل على الفريق","اترك الأسئلة المتكررة والحجوزات لـ Sawely."],[Clock3,"متاح 24 ساعة","استقبل عملاءك حتى خارج أوقات العمل."],[ShieldCheck,"لا تخسر العملاء","ابقَ الخيار الأول قبل أن يتجه العميل للمنافس."],[Languages,"عربي وإنجليزي","تواصل طبيعي يناسب عملاء الكويت والخليج."]] as const;
const industries=[["💇‍♀️","صالونات التجميل","حجز الخدمات والمواعيد والإجابة عن الأسعار."],["🦷","عيادات الأسنان","تنظيم المواعيد والرد على استفسارات المرضى."],["🏥","العيادات الطبية","استقبال الطلبات وتوجيه العميل للخدمة المناسبة."],["👔","مغاسل الملابس","طلبات الاستلام والتوصيل والأسعار بلا انتظار."],["🚗","مغاسل السيارات","حجز الباقات والمواعيد في الوقت المناسب."],["🍽️","المطاعم","الرد على الحجوزات والقائمة ومواعيد العمل."]] as const;
export default function Home(){return <><FloatingCTA/><main>
<header className="nav container"><a href="#top" aria-label="العودة إلى بداية الصفحة"><Brand/></a><nav aria-label="التنقل الرئيسي"><a href="#demo">الديمو</a><a href="#industries">الأنشطة</a><a href="#how">كيف يعمل؟</a></nav><a className="nav-cta" href={WHATSAPP_URL}>احجز عرضاً مجانياً</a></header>
<section id="top" className="hero container"><div className="hero-copy"><span className="eyebrow"><BadgeCheck/> مساعد واتساب للأعمال في الكويت والخليج</span><h1>لا تخسر أي عميل بسبب <em>تأخر الرد</em> على واتساب</h1><p>ساعد عملاءك يحجزون المواعيد، يستفسرون عن الأسعار، ويحصلون على رد فوري 24 ساعة حتى خارج أوقات العمل.</p><div className="hero-actions"><a className="button primary" href="#demo"><MessageCircle/> جرّب الديمو الآن</a><a className="button secondary" href={WHATSAPP_URL}><CalendarCheck/> احجز عرضاً مجانياً</a></div><small>تجربة فورية • بدون تسجيل • مهيأ للأعمال العربية</small></div><div className="hero-visual"><LiveDemo compact/></div></section>
<section className="problem-section"><div className="container"><div className="section-heading"><span className="kicker">المشكلة التي تحدث كل يوم</span><h2>الرد المتأخر قد يعني حجزاً ضائعاً</h2></div><div className="storyline"><article><span>1</span><b>عميل يرسل رسالة...</b><p>يسأل عن السعر أو موعد متاح.</p></article><i>←</i><article><span>2</span><b>موظفة الاستقبال مشغولة...</b><p>ومحادثات واتساب تتراكم.</p></article><i>←</i><article className="lost"><span>3</span><b>بعد دقائق...</b><p>العميل يحجز عند المنافس.</p></article></div><div className="solution-strip"><Sparkles/><p><strong>Sawely يحل المشكلة:</strong> يرد فوراً، يجيب عن الأسئلة، ويحوّل المحادثة إلى حجز.</p></div></div></section>
<section id="demo" className="demo-section container"><div className="section-heading"><span className="kicker">شاهد النتيجة بنفسك</span><h2>جرّبه بنفسك</h2><p>اسأل أي سؤال كما لو كنت أحد عملائك، وشاهد كيف تتحول المحادثة إلى حجز.</p></div><LiveDemo/><a className="button primary demo-launch" href={DEMO_URL} target="_blank" rel="noopener noreferrer">ابدأ التجربة الكاملة <ArrowLeft/></a></section>
<section id="benefits" className="outcomes-section"><div className="container"><div className="section-heading"><span className="kicker">نتائج تلمسها في نشاطك</span><h2>واتساب يعمل لصالحك، طوال الوقت</h2></div><div className="card-grid">{outcomes.map(([Icon,title,description])=><article className="outcome-card" key={title}><span><Icon/></span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
<section id="industries" className="industries container"><div className="section-heading"><span className="kicker">مصمم للأعمال المحلية</span><h2>يناسب نشاطك، مهما كان مجال خدمتك</h2><p>تجارب محادثة مهيأة لطريقة عمل الشركات في الكويت ودول الخليج.</p></div><div className="industry-grid">{industries.map(([icon,title,description])=><article className="industry-card" key={title}><span className="industry-icon">{icon}</span><h3>{title}</h3><p>{description}</p><a href={DEMO_URL} target="_blank" rel="noopener noreferrer">عرض الديمو <ArrowLeft/></a></article>)}</div></section>
<section id="how" className="how-section"><div className="container"><div className="section-heading"><span className="kicker">بسيط من أول رسالة</span><h2>ثلاث خطوات من السؤال إلى الحجز</h2></div><div className="steps"><article><span>01</span><MessageCircle/><h3>يرسل العميل رسالة</h3><p>على واتساب الذي يستخدمه كل يوم.</p></article><article><span>02</span><Zap/><h3>يحصل على رد خلال ثوانٍ</h3><p>إجابة واضحة وطبيعية بالعربية أو الإنجليزية.</p></article><article><span>03</span><CalendarCheck/><h3>يتم الحجز أو التحويل</h3><p>يؤكد الموعد أو يحوّل المحادثة إلى موظف الاستقبال.</p></article></div></div></section>
<section className="trust container"><div className="section-heading"><span className="kicker">ثقة تنمو مع عملائنا</span><h2>مصمم لرفع جودة تجربة العميل</h2></div><div className="stats"><div><strong>24/7</strong><span>استقبال مستمر</span></div><div><strong>ثوانٍ</strong><span>متوسط سرعة الرد</span></div><div><strong>عربي + English</strong><span>دعم ثنائي اللغة</span></div></div><blockquote>“نساعد الأنشطة المحلية على تحويل واتساب من صندوق رسائل مزدحم إلى قناة حجوزات فعّالة.”<cite>— فريق Sawely</cite></blockquote><p className="trust-note">قريباً: قصص نجاح وتقييمات وشعارات عملائنا.</p></section>
<section className="final-cta"><div className="container"><span className="kicker">ابدأ اليوم</span><h2>جاهز توقف خسارة العملاء؟</h2><p>احجز عرضاً مجانياً وشوف كيف يقدر Sawely يساعد نشاطك خلال دقائق.</p><div className="hero-actions"><a className="button light" href={WHATSAPP_URL}><CalendarCheck/> احجز عرضاً مجانياً</a><a className="button whatsapp" href={WHATSAPP_URL}><MessageCircle/> تواصل عبر واتساب</a></div></div></section>
</main><Footer/></>}
